version: "master-{build}"

os: Visual Studio 2017
platform:
  - x64

environment:
  winrm_user: test_user
  winrm_pass: Pass@word1

  matrix:
    - ruby_version: "24"
      train_target: winrm://test_user@localhost:5985

    - ruby_version: "25"
      train_target: winrm://test_user@localhost:5985

    - ruby_version: "26"
      train_ssl: true
      train_target: winrm://test_user@localhost:5986

clone_folder: c:\projects\train
clone_depth: 1

branches:
  only:
    - master

cache:
  - vendor/bundle -> appveyor.yml

install:
  - systeminfo
  - winrm quickconfig -q
  - ps: net user /add $env:winrm_user $env:winrm_pass
  - ps: net localgroup administrators $env:winrm_user /add
  - ps: $env:winrm_cert = (New-SelfSignedCertificate -DnsName localhost -CertStoreLocation cert:\localmachine\my).Thumbprint
  - ps: winrm create winrm/config/Listener?Address=*+Transport=HTTPS "@{Hostname=`"localhost`";CertificateThumbprint=`"$($env:winrm_cert)`"}"
  - ps: $env:PATH="C:\Ruby$env:ruby_version\bin;$env:PATH"
  - ps: Write-Host $env:PATH
  - ruby --version
  - gem --version
  - bundler --version
  - ruby -r rubygems -e "p Gem.path"

build_script:
  - bundle install --path=vendor/bundle --without integration tools

test_script:
  - SET SPEC_OPTS=--format progress
  - bundle exec rake test:windows
